---
## CI/CO para desplegar el .war de la plataforma
stages:
  - deploy

deploy_war:
  stage: deploy
  script:
   - echo "${CI_COMMIT_REF_NAME}"
  tags:
   - plataformawp
  when: always     
  environment:
    name: ${CI_COMMIT_REF_NAME}

