---
## CI/CO para desplegar el .war de la plataforma
before_script:
  - echo "$SSH_PRIVATE_KEY"
stages:
  - deploy

deploy_war:
  stage: deploy
  script:
   - echo "Hello"
  tags:
   - plataformawp
  when: always     

