---
## CI/CO para desplegar el .war de la plataforma
before_script:
  - apt update 
  - apt install -y unzip  
  - echo "${CI_COMMIT_REF_NAME}"
  - mkdir -p /root/worldprofe
  - mkdir -p /usr/local/tomcat8/webapps/plataformawp/ROOT/

stages:
  - deploy
  - war
  - reset
  - optinoal
deploy:
  stage: deploy
  script:
   -  echo "${CI_COMMIT_REF_NAME}"
   -  rm -rf /root/worldprofe
   -  rm -rf /usr/local/tomcat8/webapps/plataformawp/ROOT/*
   -  sudo git clone git@gitlab.com:frankjosue.vigilvega/worldprofe.git /root/worldprofe
  tags:
   - plataformawp
  when: always     
  only: 
    - master

deploy_war:
  stage: war
  script:
   -  echo "${CI_COMMIT_REF_NAME}"     
   -  cd /root/worldprofe/war && unzip *.war -d /usr/local/tomcat8/webapps/plataformawp/ROOT/   
  tags:
   - plataformawp
  when: always
  only:
    - master

deploy_reset:
  stage: reset
  script:
   -  sh /usr/local/tomcat8/bin/shutdown.sh
   -  sh /usr/local/tomcat8/bin/startup.sh
  tags:
   - plataformawp
  when: always
  only:
    - master


deploy_optional:
  stage: optinoal
  script:
   -  rm -rf /usr/local/tomcat8/webapps/plataformawp/ROOT/assets/* 
   -  rm -rf /usr/local/tomcat8/webapps/plataformawp/ROOT/app/* 
   -  rm  /usr/local/tomcat8/webapps/plataformawp/ROOT/index.html
   -  rm -rf /usr/local/tomcat8/webapps/plataformawp/ROOT/WEB-INF/classes/config/* 
   -  cp -r /usr/local/tomcat8/webapps/plataformawp2/ROOT/WEB-INF/classes/config/* /usr/local/tomcat8/webapps/plataformawp/ROOT/WEB-INF/classes/config/
   -  cp -r /usr/local/tomcat8/webapps/plataformawp2/ROOT/app/* /usr/local/tomcat8/webapps/plataformawp/ROOT/app/
   -  cp -r /usr/local/tomcat8/webapps/plataformawp2/ROOT/assets/* /usr/local/tomcat8/webapps/plataformawp/ROOT/assets/
   -  cp  /usr/local/tomcat8/webapps/plataformawp2/ROOT/index.html /usr/local/tomcat8/webapps/plataformawp/ROOT/index.html
  tags:
   - plataformawp
  when: always
  only:
    - master
