# ===================================================================
# Spring Boot configuration.
#
# This configuracion will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

locale:
    default: es

server:
    port: 80

spring:
    jpa:
<<<<<<< HEAD
      show-sql: false

    mail:
      host: smtp.google.com
      port: 587
      username: rosel11078@gmail.com
      password: 
      protocol: smtp
      default-encoding: UTF-8
      properties.mail.smtp:
        auth: true
        starttls.enable: true

    # social:
    #     # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
    #   google:
    #     clientId: xxxxxxxx
    #     clientSecret: xxxxxxxx
    #     # see https://developers.facebook.com/docs/facebook-login
    #   facebook:
    #     clientId: xxxxxxxx
    #     clientSecret: xxxxxxxx

properties:
  async:
      corePoolSize: 2
      maxPoolSize: 50
      queueCapacity: 10000

  paypal:
    # Datos de desarrollo
    clientID: xxxxxxxx
    clientSecret: xxxxxxxx
    environment: sandbox

  # social:
  #   redirectAfterSignIn: "/social-auth"
  #   redirectAfterSignUp: "/social-register"

  mail:
    from: rosel11078@gmail.com
    name: Pruebas de Correo

  social:
    redirectAfterSignIn: "http://localhost:9000/#/social-auth"
    redirectAfterSignUp: "http://localhost:9000/#/social-register"
=======
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.id.new_generator_mappings: true
            hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    http:
      multipart:
        max-file-size: 20Mb
        max-request-size: 20Mb
    messages:
      basename: i18n/messages
    thymeleaf:
      mode: XHTML

properties:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    security:
        authentication:
            jwt:
                secret: c2t3f0c5dXF6bV9tOV45X2RpdmlzYQ==
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
                tokenValidityInSecondsForRememberMe: 2592000
>>>>>>> 1b773029f3d9039a25912b2d7675e195a84d3e60

javamelody:
  advisor-auto-proxy-creator-enabled: false
  init-parameters:
    application-name: SIFE1701
    authorized-users: admin:worldprofe
    monitoring-path: /monitoring
    log: false
    url-exclude-pattern: (/resources/.*|/upload/.*|/templates/.*)

