# ===================================================================
# Spring Boot configuracion for the "dev" profile.
#
# This configuracion overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# locale:
#     default: es

server:
    port: 8080
    compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json


spring:
    message:
        basename: i18n/messages
        encoding: UTF-8
  # Configuración de la BASE DE DATOS
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://127.0.0.1:5432/sife1701db
        username: postgres
        password: postgres
        maximum-pool-size: 5

    application:
        url: http://plataformawp.es # URL en la que se aloja la aplicación
    profiles:
        active: prod
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jpa:
      show-sql: false

    mail: # Configuración del servidor de correo
      host: smtp.ionos.es
      port: 587
      username: admin@worldprofe.com
      password: $Adminworldprofe.2020$
      protocol: smtp
      default-encoding: UTF-8
      properties.mail.smtp:
        auth: true
        starttls.enable: true

    # social:
    #     # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
    #   google:
    #     clientId: xxxxxxxx
    #     clientSecret: xxxxxxxx
    #     # see https://developers.facebook.com/docs/facebook-login
    #   facebook:
    #     clientId: xxxxxxxx
    #     clientSecret: xxxxxxxx

properties:
  async:
      corePoolSize: 2
      maxPoolSize: 50
      queueCapacity: 10000

  paypal:
    # Datos de desarrollo
    clientID: xxxxxxxx
    clientSecret: xxxxxxxx
    environment: sandbox

  # social:
  #   redirectAfterSignIn: "/social-auth"
  #   redirectAfterSignUp: "/social-register"


 mail:
    from: admin@worldprofe.com # Configuración del email de envío
    name: WORLDPROFE
 social:
    redirectAfterSignIn: "/social-auth"
    redirectAfterSignUp: "/social-register"

javamelody:
  advisor-auto-proxy-creator-enabled: false
  init-parameters:
    application-name: SIFE1701
    authorized-users: admin:worldprofe
    monitoring-path: /monitoring
    log: false
    url-exclude-pattern: (/resources/.*|/upload/.*|/templates/.*)
